### ISSUE TITLE
Can't select lighting underglow effect > Nr. 13. in the Menu

### ISSUE THREAD

**Issue by Metamix13** [the-via/releases#236]
I'm using the Keychron Q6 Knob edition and have a Problem regarding the configuration of the lighting settings. 

By using any underglow effect with a number higher than 13. so e.g the typing heatmap. It will be selected but not activated. It stucks at Nr. 13. By closing and reopening the Application the selection is back to Nr. 13 even if it was something higher than that before closing.

There is no error message or anything that tells my why this isn't a valid selection so I guess it has to be a bug. 
I have downloaded the Windows exe with version 2.0.5 and my Keychron Q6 was already detected. 

I hope you can help me. Thanks in advance.

**Comment by plamf** [comment]
This might be the same issue even though I am using a Keychron V1:
I just noticed on my V1 that all the lighting profiles from 13 to 21 appear to be the same. I'd like to select the TYPING_HEATMAP, but it just shows RAINDROPS.
This happens on the Windows Desktop version of VIA and also the Web UI.

**Comment by smaranza** [comment]
Same issue happens also with a Keychron V3. 

I was checking the keyboard firmware available on [qmk_firmware](url) when I noticed: 

- In `config.h` the RGB animation seems to be correctly defined 
- i.e. In the ansi profile `rules.mk` (https://github.com/qmk/qmk_firmware/tree/master/keyboards/keychron/v3/ansi/rules.mk), both BACKLIGHT_ENABLE and RGBLIGHT_ENABLE are deactivated (which is quite counterintuitive)

Could this be related to the impossibility to set reactive lighting modes?

**Comment by adophoxia** [comment]
@Metamix13 and @plamf, it's because when the Q6 was added to the main QMK repo, it had 22 effects enabled compared to the 13 that boards like the Q1 and Q2 had. The JSON that's in [`the-via:master`](https://github.com/the-via/keyboards/tree/master/src/keychron/q6) do take account for the increased number of effects listed. Otherwise, you are right in that some of the options picked (like picking `TYPING_HEATMAP` which actually shows as `RAINDROPS`) are incorrect, but that's mostly due to them being defined that way. I'm gonna assume that your boards weren't flashed with the latest firmware to rectify this issue. 
@smaranza, 
>both BACKLIGHT_ENABLE and RGBLIGHT_ENABLE are deactivated (which is quite counterintuitive)
`BACKLIGHT_ENABLE` is for boards that use white non-per-key LEDs with `RGB_IGHT_ENABLE` being the equivalent for RGB LEDs. Since these boards do have per-key RGB, you may have seen the `RGB_MATRIX_ENABLE` rule enabled, so idk how that, imo, that would be counterintuitive.

**Comment by Metamix13** [comment]
Thanks @adophoxia for your detailed reply. I don't think I will risk any real issues by flashing the keyboard just to have some more RGB templates. So I can't check if this would solve the issue. 

Maybe someone else will do this and can use this issue to document their result. From my perspective you can close this issue.
Again - thanks everyone.

**Comment by GeryKapitany** [comment]
I've a Keychron Q6 ISO Knob edition. I've had the same issue that I can't change all the lighting effect. 
I've successfully updated the firmware to version 1.4 and now every effect available.
I can select them in VIA and from the keyboard.

**Comment by plamf** [comment]
Thanks @GeryKapitany! Flashing my V1 to v1.7 solved the issue for me. I can now properly select all the different lighting profiles.
