### ISSUE TITLE
Fails to start on Ubuntu: "No polkit authentication agent found"

### ISSUE THREAD

**Issue by AdamVig** [the-via/releases#67]
When I ran Via using the desktop file, it displayed the udev prompt, then nothing happened after I pressed "Continue." When I ran it from the command line and pressed "Continue" on the udev prompt, I saw the following output.
```
> via
Beginning of file
Finish Imports
Requesting lock
promppting linux access
390cd24a6ad30bec63967065a5898337
Error: No polkit authentication agent found.
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: `cd "/home/redacted"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; printf 'KERNEL==\\"hidraw*\\", SUBSYSTEM==\\"hidraw\\", MODE=\\"0666\\", TAG+=\\"uaccess\\", TAG+=\\"udev-acl
\\"' > /etc/udev/rules.d/92-viia.rules && udevadm control --reload-rules && udevadm trigger"`
}
```
I am using Ubuntu 20.10 with the i3 window manager. I found https://github.com/balena-io/etcher/issues/1179, which has some useful context on the issue. I was able to get past this error with the following command:
```
sudo via --no-sandbox
```
I can now run Via normally.

I believe this is caused by an issue with my system configuration, so the error is probably valid. However, I believe that the error _handling_ should be improved, perhaps with a top-level uncaught exception handler that displays the error message in a popup before crashing.

**Comment by itspngu** [comment]
You need an udev rule, that's what the failing command is trying to create. After that it'll run fine without the `--no-sandbox` switch.

Related to this issue: The AppImage installer fails for me when trying to create this. Likely related to me not running `polkit`. However, I'd like to suggest that

- it should fail that part silently and then notify the user that they will need to manually create an udev rule, anyone not running polkit will know how to do that
- it should check for the existence of the rule it's trying to create before trying to create it (again) and then failing

I was pointed at prepending `DISABLE_SUDO_PROMPT=1` to the AppImage invocation, which got me past that, and VIA works fine (because the rule exists).

**Comment by AdamVig** [comment]
I recently ran into the same error with balenaEtcher and was able to address it by [adding a Polkit authentication agent to my desktop environment](https://github.com/AdamVig/dotfiles/commit/2593487410a660b8d5e5e3f77bb2e1b9bd042cfb).

I stand by my suggestion to improve error handling in the application, but since this seems like a niche problem, I am going to close this issue.
