### ISSUE TITLE
Mod tap keys in VIA

### ISSUE THREAD

**Issue by TerencedzLi** [the-via/releases#74]
👋 Hello, thanks for this awesome software!

One question I had is how to set mod-taps? I'd like to have my `CAPS LOCK` key to be `CTRL` and `ESC` when tapped. I used to use QMK to do this, and I'd set the keycode to be `LCTL_T(KC_ESC)`. But I can't do the same with VIA.

I tried using the UI to assign `LC` but it won't let me select what will happen when the key is tapped. I then attempted to modify the VIA JSON itself and it doesn't recognize `LCTL_T(KC_ESC)`

**Comment by tobiasbueschel** [comment]
Hi @TerencedzLi 👋,

Have you already tried it using the `Any` button?

![image](https://user-images.githubusercontent.com/13087421/106102121-e1132f00-6179-11eb-80a6-d2002d03baca.png)

I've used it to set up e.g. `LT(1,KC_CAPS)` and it worked without problems for my board. However, I had to use `KC_CAPS` instead of `KC_CAPSLOCK` which didn't work for some reason.

Here's the QMK reference:
- https://docs.qmk.fm/#/mod_tap?id=mod-tap

**Comment by ckoehn** [comment]
I've successfully used the `Any` function with `MT(MOD_LCTL, KC_ESC)` to achieve exactly that.

**Comment by TerencedzLi** [comment]
Thanks for the help folks! I had manually entered `MT(MOD_LCTL, KC_ESC)`  in the JSON but I'll try the `ANY` method next!
