### ISSUE TITLE
Unable to open on MacOS Big Sur

### ISSUE THREAD

**Issue by evanfrawley** [the-via/releases#95]
Hi!

I'm unable to open the 1.3.1 release on MacOS Big Sur. I get this error message when I try to open:

```
"VIA" cannot be opened because the developer cannot be verified.
```

![CleanShot 2021-03-02 at 13 27 58](https://user-images.githubusercontent.com/13992385/109717677-3cf71c00-7b5b-11eb-995a-0661b6ed6386.png)

Currently on MacOS `Big Sur v11.2.1`

Any idea on how to solve this?

**Comment by EvanBancroft** [comment]
Go to your system preferences, navigate into security and privacy. Under the general tab, it should say something like "Via was blocked because it is from an unidentified developer" with a button to "Open Anyway". Click that button, there will be one more popup asking if you are sure and then you can launch it!

**Comment by evanfrawley** [comment]
@EvanBancroft thank you fellow Evan :) I forgot that was a thing! Appreciate the help.
